# Generated by Django 2.2.1 on 2019-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190529_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='hack your life', max_length=200),
        ),
    ]
