# Generated by Django 2.2.1 on 2019-05-29 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190530_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='now_date',
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
