# Generated by Django 2.2.2 on 2019-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_approval',
            field=models.BooleanField(default=False),
        ),
    ]
