# Generated by Django 2.2.1 on 2019-06-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('title', models.CharField(choices=[('01', '멋사MT'), ('02', '아이디어톤'), ('03', '해커톤'), ('04', '세션'), ('05', '기타')], max_length=2)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
